resultsDenseLatticeMult = runtests('Lattice\dense_lattice_mult_test.m')
resultsDenseLatticeSolve = runtests('Lattice\dense_lattice_solve_test.m')
resultsSparseLatticeMult = runtests('SparseLattice\sparse_lattice_mult_test.m')
resultsSparseLatticeSolve = runtests('SparseLattice\sparse_lattice_solve_test.m')
resultsDenseMIAMult = runtests('MIA\dense_mia_mult_test.m')
resultsDenseMIAAssign = runtests('MIA\dense_mia_assign_test.m')